services:
  vw:
    image: vaultwarden/server:latest
    restart: always
    healthcheck:
      test: curl --fail http://localhost:80/alive || exit 1
      interval: 40s
      timeout: 30s
      retries: 3
      start_period: 60s
    volumes:
      - ./vw-data:/data
    depends_on:
      - db
    ports:
      - 80:80
    env_file:
      - .db.env
      - .vw.env
    networks:
      - vw
      - db
  db:
    image: postgres:16.4-alpine
    restart: always
    healthcheck:
      test: pg_isready -U vaultwarden -d vaultwarden
      interval: 40s
      timeout: 30s
      retries: 3
      start_period: 60s
    volumes:
      - ./db-data:/var/lib/postgresql/data
    env_file:
      - .db.env
    networks:
      - db
      - backup
  backup:
    image: prodrigestivill/postgres-backup-local
    restart: always
    healthcheck:
      test: curl --fail http://localhost:8080 || exit 1
      interval: 40s
      timeout: 30s
      retries: 3
      start_period: 60s
    volumes:
      - ./backup-data:/backups
    depends_on:
      - db
    env_file:
      - .db.env
      - .backup.env
    networks:
      - backup
  cloudflared:
    image: cloudflare/cloudflared:2024.8.2
    restart: unless-stopped
    user: root
    command: tunnel run
    depends_on:
      - vw
    env_file:
      - .env.cloudflared
    networks:
      - vw

networks:
  vw:
  db:
  backup:
